---
- name: Copy init.d script for stem-cell-differentiate
  copy: src=files/stem-cell-differentiate dest=/etc/init.d/stem-cell-differentiate owner=root group=root mode=0751

- name: Make directory for stem cell
  file: path=/opt/stem_cell state=directory owner=root group=root mode=0775

- name: Copy stem_cell python application
  copy: src=../../../../stem_cell/ dest=/opt/stem_cell/ owner=root group=root mode=0751

- name: Enable stem-cell service
  service: name=stem-cell-differentiate enabled=yes
