---
- name: Update AMI yum packages to latest
  yum: name=* state=latest

- name: Ensure yum-python26 is installed
  yum: name=yum-python26 state=present

- name: Copy init.d script for stem-cell-differentiate
  copy: src=files/stem-cell-differentiate dest=/etc/init.d/stem-cell-differentiate owner=root group=root mode=0751

- name: Copy the stem-cell-variable script into /usr/local/bin
  copy: src=files/stem-cell-variable dest=/usr/local/bin owner=root group=root mode=0755

- name: Symlink stem-cell-variable
  file: src=/usr/local/bin/stem-cell-variable dest=/usr/bin/stem-cell-variable state=link

- name: Make directory for stem cell
  file: path=/opt/stem_cell state=directory owner=root group=root mode=0775

- name: Copy stem_cell python application
  copy: src=../../../../stem_cell/ dest=/opt/stem_cell/ owner=root group=root mode=0751

- name: Disable strict key checking for github.com
  copy: src=files/ssh/config dest=/root/.ssh/config owner=root group=root mode=0400

- name: Copy ssh-git wrapper script
  copy: src=files/ssh-git.sh dest=/opt/ssh-git.sh owner=root group=root mode=751

- name: Enable stem-cell service
  service: name=stem-cell-differentiate enabled=yes
