---
# Install required dependencies on stem-cell build image

- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts


- hosts: dynamically_created_hosts
  become: true
  become_user: root
  become_method: sudo
  roles:
    - geerlingguy.ansible
    - stem-cell
